version: "3"

services:
  user-service:
    build:
      context: ./../
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
    environment:
      APP_ENV: production
    networks:
      lsu_network:
        ipv4_address: 192.168.0.7

networks:
  lsu_network:
    external: true
